-- ES 字段映射表初始化脚本
USE knowledge_base;

CREATE TABLE IF NOT EXISTS es_field_mapping (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    english_name VARCHAR(200) NOT NULL UNIQUE COMMENT '英文字段名',
    chinese_name VARCHAR(200) NOT NULL COMMENT '中文字段名',
    description VARCHAR(500) COMMENT '字段描述',
    is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    sort_order INT DEFAULT 0 COMMENT '排序顺序',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_english_name (english_name),
    INDEX idx_chinese_name (chinese_name),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ES字段中英文映射表';

-- 从 CSV 文件导入初始数据（需要手动执行或使用 Python 脚本）
-- 示例数据：
INSERT INTO es_field_mapping (english_name, chinese_name, description) VALUES
('EVENT_NUMBER', '事件ID', ''),
('NETWORK_TYPE_TOP', '一级专业ID', ''),
('ORG_SEVERITY', '事件等级ID', ''),
('REGION_NAME', '地市', ''),
('CITY_NAME', '县市', ''),
('ALARM_SOURCE', '告警来源', ''),
('EQP_LABEL', '网元名称', ''),
('EQP_OBJECT_CLASS', '设备类型ID', ''),
('VENDOR_NAME', '设备厂家名称', ''),
('VENDOR_ID', '设备厂家ID', ''),
('LOCATE_INFO', '事件定位信息', ''),
('NETWORK_TYPE', '二级专业ID', ''),
('EQP_OBJECT_NAME', '设备类型', ''),
('ORDER_TIME', '工单派单时间', ''),
('MAINTAIN_TEAM', '主派维护组', ''),
('MAIN_NET_SORT_ONE', '网络一级分类', ''),
('MAIN_NET_SORT_TWO', '网络二级分类', ''),
('MAIN_NET_SORT_THREE', '网络三级分类', ''),
('NETWORK_SUB_TYPE_NAME', '二级专业名称', ''),
('NETWORK_TYPE_NAME', '一级专业名称', ''),
('EVENT_SOURCE', '事件来源', ''),
('EVENT_STANDARD_FLAG', '事件标准化标识', ''),
('EVENT_NAME', '事件标题', ''),
('ALARM_NAME', '告警标题', ''),
('EVENT_STANDARD_NAME', '事件标准名', ''),
('EVENT_STANDARD_ID', '事件标准ID', ''),
('ALARM_STANDARD_NAME', '告警标准名', ''),
('ALARM_STANDARD_ID', '告警标准ID', ''),
('ALARM_LEVEL', '网管告警级别', ''),
('EVENT_TIME', '事件发生时间', ''),
('CREATION_EVENT_TIME', '事件发现时间', ''),
('TIME_STAMP', '事件发现时间-亿阳', ''),
('CANCEL_TIME', '事件清除时间', ''),
('FP0_FP1_FP2_FP3', '事件流水号', ''),
('ORDER_ID', '工单号', ''),
('ORG_FP0_FP1_FP2_FP3', '亿阳事件流水号', ''),
('CFP0_CFP1_CFP2_CFP3', '事件清除FP', ''),
('REDEFINE_SEVERITY', '省内网管告警级别', ''),
('TYPE_KEYCODE', '类别关键字', ''),
('NE_LOCATION', '设备定位信息', ''),
('SITE_TYPE', '站点类型', ''),
('SUB_ALARM_TYPE', '事件子类型', ''),
('EVENT_CAT', '事件描述', ''),
('TIME_STAMP_C', '事件清除发现时间', ''),
('OBJECT_CLASS', '告警对象设备类型', ''),
('BUSINESS_SYSTEM', '业务系统', ''),
('IS_MATCH_DISPATCH_RULES', '是否符合派单规则', ''),
('START_TIME', '派单开始时间', ''),
('DISPATCH_TYPE', '派单方式', ''),
('PROCESS_STATE', '流程状态', ''),
('END_TIME', '派单结束时间', ''),
('DISPATCH_LEVEL', '省内派单级别', ''),
('ORDER_STATUS', '派单状态', ''),
('DISPATCH_REASON', '派单描述信息', ''),
('RULE_ID', '派单规则ID', ''),
('DELAY_TIME', '延迟时间', ''),
('PORT_NUM', '采集端口号', ''),
('NE_ADMIN_STATUS', '告警对象管理状态', ''),
('IS_RELATED', '是否子事件', ''),
('IS_ROOT', '是否根事件', ''),
('ROOT_EVENT_FP', '关联根事件FP', ''),
('EVENT_EXPLANATION', '事件扩展信息', ''),
('EVENT_SUMMARY', '预处理步骤及结果', ''),
('FAULT_DIAGNOSIS', '故障初判', ''),
('EVENT_EFFECT', '事件影响', ''),
('EVENT_REASON', '事件定界定位', ''),
('MACHINE_ROOM_INFO', '机房信息', ''),
('SERVICE_EFFECT_STATUS', '影响业务情况', ''),
('EVENT_ROOT_CATEGORY', '故障根因分类', ''),
('REMOTE_OBJECT_CLASS', '对端设备类型', ''),
('RELATED_MAINTAIN_GROUP', '抄送维护组', ''),
('ASSIGN_TENANCE_GROUP', '分派维护组', ''),
('BUSINESS_LEVEL', '业务层级', ''),
('REMOTE_EQUIPMENT_NAME', '对端设备名称', ''),
('FAULT_TYPE_ID', '故障类型', ''),
('FAULT_SUB_TYPE_ID', '故障子类型', ''),
('IS_EFFECT_BUSINESS', '是否影响业务', ''),
('SERV_EFFECT_TYPE', '影响业务类型', ''),
('ROOT_NETWORK_TYPE_TOP', '根因专业', ''),
('EVENT_ROOT_CATEGORY_ID', '根因专业ID', ''),
('JT_DISPATCH_STATUS_ID', '集团派单状态ID', ''),
('JT_DISPATCH_STATUS_DESC', '集团派单状态描述', ''),
('ORDER_TYPE', '工单类型', ''),
('AUTO_RECEIPT_RULE_NAME', '自动回单规则名称', ''),
('AUTO_RECEIPT_STATE', '自动回单状态', ''),
('AUTO_RECEIPT_REASON', '自动回单描述信息', ''),
('CANCEL_COLLECT_TIME', '清除发现时间', ''),
('REMOTE_BUSINESS_LAYER_NAME', '对端业务层级', ''),
('LINE_BUSINESS_LAYER_NAME', '线路层级', ''),
('MACHINE_ROOM_GRADE', '机房信息', ''),
('PROJ_INTERFERENCE_FLAG', '干扰标识', ''),
('PROJ_INTERFERENCE_TYPE', '干扰描述', ''),
('ALARM_RESOURCE_STATUS', '告警工程状态', ''),
('PROJ_END_TIME', '工程结束时间', ''),
('PROJ_START_TIME', '工程开始时间', ''),
('PROJ_OA_FILE_ID', '网元工程公文号', ''),
('PROJ_OA_FILE_CONTENT', '网元工程公文正文', ''),
('PROJ_NAME', '工程名', ''),
('EVENT_TYPE_ID', '事件类型', ''),
('INTERFERENCE_FLAG', '干扰标识', ''),
('MASTER_EVENT_FP', '顶级主事件FP', ''),
('BUSINESS_LAYER_NAME', '业务层级', ''),
('ROOM_ID', '机房CUID', ''),
('MAINTAIN_TEAM_SOURCE', '主派维护组来源', ''),
('TRANSFER_STATUS', '通知单转处理单标识', '')
ON DUPLICATE KEY UPDATE chinese_name=VALUES(chinese_name);
